swarnade/webdesign-switch

- design_button/kom-senapati-1.css
- index.html
> swipe right button

- design_button/shikha.css
- index.html
I have added a new button . #33
> Added a new button

- design_button/RatnojitSaha-1.css
- design_button/RatnojitSaha-10.css
- design_button/RatnojitSaha-2.css
- design_button/RatnojitSaha-3.css
- design_button/RatnojitSaha-4.css
- design_button/RatnojitSaha-5.css
- design_button/RatnojitSaha-6.css
- design_button/RatnojitSaha-7.css
- design_button/RatnojitSaha-8.css
- design_button/RatnojitSaha-9.css
- index.html
10 different buttons with and without animations are added!!
issue no - #37 
contributing platform - JWOC 2024
> [ADDED] 10 new buttons

- design_button/shahilaf_01.css
- index.html
close as #69 
this is how its look like...
> new-button added

- css/fdback.css
- css/main.css
- feedback.html
- index.html
Created an feedback page using HTML and CSS added the functionality of sending email WEB3API. Users can directly send Email about what he wanted to know about.
#ISSUE 22  COMPLETED
> CREATED FEEDBACK PAGE

- readme.md
> fix: fix readme typos

- design_button/pranjal.css
- index.html
Added new style button
Closes #65
> new button added

- design_button/shahilaf_01.css
- index.html
> fixed height ui issue

- css/main.css
Closes #94 
made the webpage responisive.
> made the page responsive

- design_button/Anjalikumari123456.css
- index.html
> Added new button

- readme.md
fix issue : #101 
There was a need of a local installation video of the project in readme.md.
> Update video in readme.md.

- design_button/ASIF-MANDAL.css
- heelo.html
I added a new button please check and approve
> Add a New Button

- .vscode/settings.json
- css/main.css
- index.html
Added Scroll Animations to make the website look more beautiful. 
Issue No. = #97
> Added Scroll Animations 

- css/main.css
- infopage/index.html
- infopage/style.css
Added footer and navbar to info page and also done some changes that make the to look more good , and also improved the ui of the page , please review my pull request.
> Added footer and navbar to info page

- design_button/beprodeep4718.css
- index.html
**hover on the button, you will see a animation happend**
#121
> hover animation

- css/main.css
- index.html
Title : Add a Search function
Issue : #118 
[screen-capture (3).webm](https://github.com/swarnade/webdesign-switch/assets/111490250/4c2796c5-88ca-4870-bc36-b589c41b914d)
> Added Searching Function

- .vscode/settings.json
- design_button/AftabShare.css
- index.html
FEAT share button added 
fixed #134
close #134 
Video
https://github.com/swarnade/webdesign-switch/assets/125949765/41ea7f12-cf65-4f2b-8657-2468a0bc7274
> FEAT share button added   

- css/main.css
- design_button/RatnojitSaha-11.css
- design_button/RatnojitSaha-12.css
- design_button/RatnojitSaha-13.css
- design_button/RatnojitSaha-14.css
- design_button/RatnojitSaha-15.css
- footer_main.css
- index.html
NEW 5 BUTTONS ADDED MADE USING HTML CSS .
A FOOTER ADDED IN MAIN PAGE USING HTML CSS AND JS
ISSUE NO - #110 
JWOC 2024
> New 5 buttons added with a footer in main page

- infopage/index.html
- infopage/style.css
#122 I added responsive hamburger menu to info page , please review my pull request.
> Added responsive hamburger menu to info page

- app.js
- css/main.css
- design_button/AftabShare.css
- index.html
Title : Add light mode & dark mode
issue: #132 
Changes : **Fixed some UI bugs**, and added a toggle button at navbar to toggle between light and dark mode.
> Added Light & Dark mode

- css/fdback.css
hover effect on social media handles on feedback page. under jwoc 2024
> hover effect on feedback page

- design_button/Sanglap-Halder.css
- index.html
I have added a new button which is golden in color and become black on hovering with a shiny white option "Button".
> Added a new button with hover effect

- infopage/style.css
#151 Fixed the repsonsiveness of info page , please check my pull request
> I made the info page responsive

- design_button/vishal.css
- index.html
> Add neumorphism button completed #147

- css/main.css
Fixed alignment of theme toggle button on medium and small screens.
> fixed alignment of toggle button

- footer_main.css
> Z index fixed for footer.

- .vscode/settings.json
- design_button/SuvayuN-1.css
- design_button/SuvayuN-2.css
- design_button/SuvayuN-3.css
- design_button/SuvayuN-4.css
- design_button/SuvayuN-5.css
- design_button/SuvayuN-6.css
- design_button/SuvayuN-7.css
- design_button/SuvayuN-8.css
- index.html
I added 8 buttons under issue #163 as a contribution under JWOC'24
> Added 8 buttons as a contribution under JWOC'24

- css/main.css
#183 I had added a customised scrollbar , please check my pull request
> Added customised scrollbar

- design_button/shahilaf_01.css
- footer_main.css
- index.html
#190 I had fixed footer and the alignments of the buutons properly , please check my pull request.
> #190 fixed the issue

- design_button/zul132-10.css
- design_button/zul132-3.css
- design_button/zul132-4.css
- design_button/zul132-5.css
- design_button/zul132-6.css
- design_button/zul132-7.css
- design_button/zul132-8.css
- design_button/zul132-9.css
- index.html
I've added 8 new Animated buttons as shown in the video below.
closes issue: #182  under JWOC 2024
https://github.com/swarnade/webdesign-switch/assets/98112914/0826453a-3bca-4693-a1ea-44dcec7d69b7
> Added 8 new Animated Buttons

- design_button/RatnojitSaha-16.css
- design_button/RatnojitSaha-17.css
- design_button/RatnojitSaha-18.css
- design_button/RatnojitSaha-19.css
- design_button/RatnojitSaha-20.css
- design_button/RatnojitSaha-21.css
- design_button/RatnojitSaha-22.css
- design_button/RatnojitSaha-23.css
- index.html
8 new buttons added
using html css
closes #154 
JWOC 2024
> 8 butttons added

- css/rateUs.css
- index.html
- rateUs.html
- rateUs.js
Added Rate Us Page ! Issue No = #191 .
> Added Rate Us Page

- index.html
> completion of info page
